

# Data Setup ------------------------------------------------------------------------------------------------------


start.date = "2015-12-02" 
end.date = "2020-12-31"
project = "Call For Data 2022"
save_location = "//deqhq1/WQASSESSMENT/2022IRFiles/DataSources/NWIS/"
USGS_stations = '422620122004300'
statcds = c("00001", "00002", "00003", "00008")
# 00001 = max, 00002 = min, 00003 = mean, 00008 = median
pCodes = c("00010", "00400", "00300", "00301")



# Temperature -----------------------------------------------------------------------------------------------------

# The mean temperature is for 30 cm from bottom, so we will drop it.
#NWIS does not report mean temp from top for this time period

print("Query NWIS Temperature begin....")
nwis.sum.stats.temp0 <- dataRetrieval::readNWISdv(siteNumbers = USGS_stations,
                                                 parameterCd = "00010",
                                                 startDate = start.date,
                                                 endDate = end.date,
                                                 statCd = statcds)

print("Query NWIS Temperature end")

nwis.sum.stats.temp0<- dataRetrieval::renameNWISColumns(nwis.sum.stats.temp0)


nwis.sum.stats.temp <- nwis.sum.stats.temp0 %>%
  select(agency_cd, site_no, Date,
         Wtemp_Max,
         Wtemp_Max_cd,
         `30.cm.from.top_Wtemp_Min`,
         `30.cm.from.top_Wtemp_Min_cd`,
         Wtemp,
         Wtemp_cd) %>%
  rename(Wtemp_Min = `30.cm.from.top_Wtemp_Min`,
         Wtemp_Min_cd = `30.cm.from.top_Wtemp_Min_cd`)

# lag uses 6 because the 7 day moving average is inclusive of the date
# If 1 day is missing from period, do not caluclate average
temp4ma <- nwis.sum.stats.temp %>%
  dplyr::arrange(site_no, Date) %>%
  dplyr::group_by(site_no) %>%
  dplyr::mutate(startdate = dplyr::lag(Date, 6, order_by = Date),
                # flag out which result gets a moving average calculated
                calcma = ifelse(startdate == (Date - 6), 1, 0 )) %>%
  dplyr::mutate(ma = ifelse(calcma == 1, round(zoo::rollmean(x = Wtemp_Max, 7, align = "right", fill = NA),1) , NA ))



nwis.sum.stats.temp.gather <- temp4ma %>%
  tidyr::gather(Wtemp_Max,
                Wtemp,
                Wtemp_Min,
                ma, key = "stat", value = "result", na.rm = TRUE) %>%
  dplyr::mutate(qual = ifelse(stat == "Wtemp_Max" | stat == "ma", Wtemp_Max_cd,
                              ifelse(stat == "Wtemp", Wtemp_cd,
                                     ifelse(stat == "Wtemp_Min", Wtemp_Min_cd, "ERROR" )))) %>%
  dplyr::select(agency_cd, site_no, Date, stat, result, qual, startdate) %>%
  dplyr::arrange(site_no, Date)


nwis.sum.stats.temp.AWQMS <- nwis.sum.stats.temp.gather %>%
  dplyr::ungroup() %>%
  dplyr::transmute(CharID = "Temperature, water",
                   Result = result,
                   Unit = "deg C",
                   Method = "THM01",
                   RsltType = "Calculated",
                   Qualcd = qual,
                   StatisticalBasis = dplyr::case_when(stat == "ma" ~"7DMADMax",
                                                       stat == "Wtemp_Max" ~ "Daily Maximum",
                                                       stat == "Wtemp" ~ "Daily Mean",
                                                       stat == "Wtemp_Min" ~ "Daily Minimum",
                                                       TRUE ~  "ERROR"),
                   RsltTimeBasis = ifelse(StatisticalBasis == "7DMADMax", "7 day", "1 Day" ),
                   DEQ_RsltComment = ifelse(StatisticalBasis == "7DMADMax", "Generated by ORDEQ", "" ),
                   ActivityType = "FMC",
                   SiteID = site_no,
                   SmplColMthd = "ContinuousPrb",
                   SmplColEquip = "Probe/Sensor",
                   SmplDepth = 30,
                   SmplDepthUnit = "cm",
                   SmplColEquipComment = "",
                   Samplers = "",
                   SmplEquipID = "Continuous Probe",
                   Project = project,
                   ActStartDate = Date,
                   ActStartTime = "0:00",
                   ActStartTimeZone = "PST",
                   ActEndDate = Date,
                   ActEndTime = "0:00",
                   ActEndTimeZone = "UTC",
                   AnaStartDate = "",
                   AnaStartTime = "",
                   AnaStartTimeZone = "",
                   AnaEndDate = "",
                   AnaEndTime = "",
                   AnaEndTimeZone = "",
                   ActComment = "",
                   ActivityID = paste0(SiteID, ":", gsub("-","",ActStartDate), ":", ActivityType)
  ) %>%
  dplyr::filter(Qualcd != 'P Eqp',
                Qualcd != 'P Dis',
                Qualcd != 'P Ssn',
                Qualcd != 'A e',
                Qualcd != 'P e') %>%
  filter(StatisticalBasis != "Daily Mean")

class(nwis.sum.stats.temp.AWQMS$SiteID) <- c("NULL", "number")



# pH --------------------------------------------------------------------------------------------------------------

print("Query NWIS pH begin....")

# Commenting out due to not using contiuous pH for assessment
nwis.cont.ph <- dataRetrieval::readNWISuv(siteNumbers = USGS_stations,
                                          parameterCd = "00400",
                                          startDate = start.date,
                                          endDate = end.date)
print("Query NWIS pH end")




nwis.cont.ph <- dataRetrieval::renameNWISColumns(nwis.cont.ph)

nwis.cont.ph <- nwis.cont.ph %>%
  select(agency_cd,site_no, dateTime, `30.cm.from.top_pH_Inst`, `30.cm.from.top_pH_Inst_cd`, tz_cd ) %>%
  rename(pH_Inst = `30.cm.from.top_pH_Inst`,
         pH_Inst_cd = `30.cm.from.top_pH_Inst_cd`)

nwis_ph_results <- nwis.cont.ph %>%
  #filter out rejected
  dplyr::filter(pH_Inst_cd != 'P Eqp',
                pH_Inst_cd != 'P Dis',
                pH_Inst_cd != 'P Ssn',
                pH_Inst_cd != 'A e',
                pH_Inst_cd != 'P e') %>%
  dplyr::transmute('Monitoring_Location_ID' = site_no,
                   "Activity_start_date" = format(dateTime, "%Y/%m/%d"),
                   'Activity_Start_Time' =format(dateTime, "%H:%M:%S"),
                   'Activity_Time_Zone' = tz_cd,
                   'Equipment_ID' = site_no,
                   'Characteristic_Name' = "pH",
                   "Result_Value" = pH_Inst,
                   "Result_Unit" = "pH Units",
                   "Result_Status_ID" = pH_Inst_cd)


pH_deployments <-   nwis_ph_results %>%
  dplyr::group_by(Monitoring_Location_ID, Equipment_ID) %>%
  dplyr::summarise(Activity_start_date_time = min(Activity_start_date),
                   Activity_end_date_time  = max(Activity_start_date),
                   Activity_start_end_time_Zone = dplyr::first(Activity_Time_Zone)) %>%
  dplyr::ungroup() %>%
  dplyr::mutate(Media = "Water",
                Media_subdivision = "Surface Water",
                Project_ID = project,
                Alternate_Project_ID = "",
                Alternate_Project_ID2 = "",
                Frequency_on_minutes = "",
                Depth_in_m = "0.3")


openxlsx::write.xlsx(pH_deployments, file = paste0(save_location, "422620122004300-NWIS_continuous_pH_Deployments.xlsx"))


openxlsx::write.xlsx(nwis_ph_results, file = paste0(save_location, "422620122004300-NWIS_continuous_pH_AWQMS_data.xlsx"))



# Do --------------------------------------------------------------------------------------------------------------



print("Query NWIS DO begin....")
nwis.sum.stats.DO <-dataRetrieval::readNWISdv(siteNumbers = USGS_stations,
                                              parameterCd = "00300",
                                              startDate = start.date,
                                              endDate = end.date,
                                              statCd = statcds)

print("Query NWIS DO end")

nwis.sum.stats.DO <- dataRetrieval::renameNWISColumns(nwis.sum.stats.DO)

nwis.sum.stats.DO <- nwis.sum.stats.DO %>%
  select(agency_cd, site_no, Date, 
         `30.cm.from.top_DO_Max`,
         `30.cm.from.top_DO_Max_cd`,
         `30.cm.from.top_DO_Min`,
         `30.cm.from.top_DO_Min_cd`,
         DO,
         DO_cd) %>%
  rename(DO_Max= `30.cm.from.top_DO_Max`,
         DO_Max_cd = `30.cm.from.top_DO_Max_cd`, 
         DO_Min = `30.cm.from.top_DO_Min`,
         DO_Min_cd = `30.cm.from.top_DO_Min_cd`)

# Calculate moving averages. If 1 or more daya are missing from period, do not caluclate average
DO4ma <- nwis.sum.stats.DO %>%
  dplyr::arrange(site_no, Date) %>%
  dplyr::group_by(site_no) %>%
  dplyr::mutate(startdate7 = dplyr::lag(Date, 6, order_by = Date),
                # flag out which result gets a moving average calculated
                calc7ma = dplyr::case_when(is.na(startdate7) ~ 0,
                                           startdate7 == (Date - lubridate::days(6)) ~ 1,
                                           TRUE ~ 0 ),
                startdate30 = dplyr::lag(Date, 29, order_by = Date),
                calc30ma = ifelse(startdate30 == (Date - 29), 1, 0 )) %>%
  dplyr::mutate(ma.mean7 = ifelse(calc7ma == 1, round(zoo::rollmean(x = DO, 7, align = "right", fill = NA),1) , NA ),
                ma.mean30 = ifelse(calc30ma == 1, round(zoo::rollmean(x = DO, 30, align = "right", fill = NA),1) , NA ),
                ma.min7 = ifelse(calc7ma == 1, round(zoo::rollmean(x = DO_Min, 7, align = "right", fill = NA),1) , NA ))


nwis.sum.stats.DO.gather <- DO4ma %>%
  tidyr::gather(DO_Max, DO, DO_Min, ma.mean7, ma.mean30,ma.min7,   key = "stat", value = "result", na.rm = TRUE) %>%
  dplyr::mutate(qual = ifelse(stat == "DO_Max", DO_Max_cd,
                              ifelse(stat == "DO" | stat == "ma.mean7" | stat == "ma.mean30", DO_cd,
                                     ifelse(stat == "DO_Min" | stat == "ma.min7", DO_Min_cd, "ERROR" )))) %>%
  dplyr::select(agency_cd, site_no, Date, stat, result, qual, startdate7, startdate30 )


nwis.sum.stats.DO.AWQMS <- nwis.sum.stats.DO.gather %>%
  dplyr::ungroup() %>%
  dplyr::transmute(CharID = "Dissolved oxygen (DO)",
                   Result = result,
                   Unit = "mg/L",
                   Method = "LUMIN",
                   RsltType = "Calculated",
                   Qualcd = qual,
                   StatisticalBasis = dplyr::case_when(stat == "ma.mean7" ~"7DMADMean",
                                                       stat == "DO_Max" ~"Daily Maximum",
                                                       stat == "DO" ~"Daily Mean",
                                                       stat == "DO_Min" ~ "Daily Minimum",
                                                       stat == "ma.mean30" ~ "30DMADMean",
                                                       stat == "ma.min7" ~ "7DMADMin",
                                                       TRUE ~ "ERROR"),
                   RsltTimeBasis = ifelse(StatisticalBasis == "7DMADMean" | StatisticalBasis == "7DMADMin", "7 day",
                                          ifelse(StatisticalBasis == "30DMADMean", "30 Day", "1 Day" )),
                   DEQ_RsltComment = ifelse(StatisticalBasis == "7DMADMean" |
                                              StatisticalBasis == "7DMADMin" |
                                              StatisticalBasis == "30DMADMean", "Generated by ORDEQ", "" ),
                   ActivityType = "FMC",
                   SiteID = site_no,
                   SmplColMthd = "ContinuousPrb",
                   SmplColEquip = "Probe/Sensor",
                   SmplDepth = 30,
                   SmplDepthUnit = "cm",
                   SmplColEquipComment = "",
                   Samplers = "",
                   SmplEquipID = "Continuous Probe",
                   Project = project,
                   ActStartDate = Date,
                   ActStartTime = "0:00",
                   ActStartTimeZone = "PST",
                   ActEndDate = Date,
                   ActEndTime = "0:00",
                   ActEndTimeZone = "UTC",
                   AnaStartDate = "",
                   AnaStartTime = "",
                   AnaStartTimeZone = "",
                   AnaEndDate = "",
                   AnaEndTime = "",
                   AnaEndTimeZone = "",
                   ActComment = "",
                   ActivityID = paste0(SiteID, ":", gsub("-","",ActStartDate), ":", ActivityType)) %>%
  dplyr::arrange(SiteID, ActStartDate)%>%
  dplyr::filter(Qualcd != 'P Eqp',
                Qualcd != 'P Dis',
                Qualcd != 'P Ssn',
                Qualcd != 'A e',
                Qualcd != 'P e')

class(nwis.sum.stats.DO.AWQMS$SiteID) <- c("NULL", "number")



# Put it together -------------------------------------------------------------------------------------------------

NWIS_sum_stats_data <- dplyr::bind_rows(nwis.sum.stats.temp.AWQMS
                                        ,nwis.sum.stats.DO.AWQMS)

write.xlsx(NWIS_sum_stats_data,  file = paste0(save_location, "422620122004300-NWIS_sum_stat_AWQMS_data.xlsx"))
